### ISSUE TITLE
Please integrate into Base Julia!!!

### ISSUE THREAD

**Issue by StefanKarpinski** [Keno/REPL.jl#8]
I know this must be useable because you've been using it _forever_. Can we also have it please? If you outline what needs to be done, I can help.

cc: @carlobaldassi, @JeffBezanson, @ViralBShah

**Comment by ViralBShah** [comment]
+Inf

**Comment by ivarne** [comment]
I have the impression that many developers want to contribute to the REPL, but we hold them back, because we say we will get rid of readline.

+BigFloat(Inf)

**Comment by StefanKarpinski** [comment]
I have that impression as well.

``` julia
with_bigfloat_precision(1024) do
  big(Inf)
end
```

**Comment by Keno** [comment]
Ok, fine, I get it. Let's get this done.

**Comment by StefanKarpinski** [comment]
:D

**Comment by Keno** [comment]
Alright, first order of business is to get people to try this and make sure bugs are getting fixed. To that end, I added the script needed to run the repl from the command line. To try it out, instead of running `julia`, run `julia ~/.julia/REPL/scripts/repl.jl`. At this point, my workflow is fairly well tested, but I'm sure other people are doing things I usually don't, so there'll be bugs.

**Comment by ViralBShah** [comment]
I had to checkout the master of TERM.jl and Readline.jl manually first. Then, I get a whole bunch of ambiguity warnings and the `banner_color` error. If I comment out that line, I get this error:

```
ERROR: uv_error not defined
 in size at /Users/viral/.julia/Terminals/src/Terminals.jl:453
 in refreshMultiLine at /Users/viral/.julia/Readline/src/Readline.jl:160
 in activate at /Users/viral/.julia/Readline/src/Readline.jl:859
 in activate at /Users/viral/.julia/Readline/src/Readline.jl:864
 in prompt! at /Users/viral/.julia/Readline/src/Readline.jl:938
 in run_interface at /Users/viral/.julia/Readline/src/Readline.jl:923
 in run_repl at /Users/viral/.julia/REPL/src/REPL.jl:473
 in anonymous at no file:34
while loading /Users/viral/.julia/REPL/scripts/repl.jl, in expression starting on line 9
```

**Comment by ViralBShah** [comment]
Ok, I had to also update `Terminals` to master. After that, no errors or ambiguity warnings.

**Comment by ViralBShah** [comment]
That could easily update a lot of packages to master, unknowingly. Perhaps a warning along the lines would be good to have though, so that the user can decide.

**Comment by Keno** [comment]
All reported bugs fixed. Keep them coming.

**Comment by StefanKarpinski** [comment]
My feeling is that this is pretty close to being ready for integration into Base. There's a few more bugs to iron out, but it already serves as a great drop-in replacement for the old REPL for me.

**Comment by StefanKarpinski** [comment]
Ok, there's no obvious issues left. I say we merge this puppy into Base. What's the procedure?

**Comment by ViralBShah** [comment]
Currently, any exception makes the script quit. I guess, we just need to get to a point where this is handled well, and it doesn't quit.

**Comment by ivarne** [comment]
We do not need to make the new REPL default, to integrate it to Base. It can live alongside the old for a while.

**Comment by nolta** [comment]
I hope i'm not stepping on anyone's toes, but i took a crack at this: https://github.com/JuliaLang/julia/compare/mn;newrepl

**Comment by Keno** [comment]
My toes are too busy with school work to be stepped on by anybody ;)

**Comment by jariou** [comment]
I followed instructions here: https://github.com/loladiro/REPL.jl/issues/34

I am on Windows 7. Here is what I get

C:\Users\Jacques>C:\Julia\Julia_0.3.0-prerelease\bin\julia.exe C:/Users/Jacques/.julia/v0.3/REPL/scripts/repl.jl
Warning: redefining constant CPU_CORES
ERROR: spawn: no such file or directory (ENOENT)
 in _jl_spawn at process.jl:212
while loading C:\Users\Jacques.julia\v0.3\REPL\scripts\repl.jl, in expression s
tarting on line 8

blas_num_threads=4

C:\Users\Jacques>

**Comment by ivarne** [comment]
What version of julia are you using? I think the CPU_CORES warning was fixed a while back, and it is very rewarding to debug issues that might already have been fixed. Can you try to update if your nightly release is more than a week old?

**Comment by jariou** [comment]
It is definitely more than a few weeks old. I don't build it locally, it is an install from perhaps 6 or 8 weeks ago. If you can point me to instructions to update an installed version to the latest and greatest binaries and supporting files, I'll be happy to give feedback on the issue.

**Comment by ivarne** [comment]
I would guess that it would work to follow the instructions on [julialang.org/downloads](http://julialang.org/downloads/). I don't have access to a windows computer, so I have not tried. @ihnorton also just published prebundled version https://github.com/JuliaLang/julia/pull/6270#issuecomment-38756087, that you might give a try.

**Comment by jariou** [comment]
Thanks,

I'll give it a try tonight and report. 

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by jariou** [comment]
I downloaded @ihnorton's prebundled version and I still have problems. See beloaw, first a launch of julia-basic with Pkg.update() within that session. Then I exit and launch with REPL.jl and get error:
ERROR: spawn: no such file or directory (ENOENT)
 in _jl_spawn at process.jl:212
while loading c:\users\Jacques.julia\v0.3\REPL\scripts\repl.jl, in expression s
tarting on line 8

blas_num_threads=4

## See the two complete launches below

C:\Julia\JuliaRepl\Julia 0.3.0-prerelease\bin>julia-basic
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" to list help topics
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.0-prerelease+2175 (2014-03-26 21:52 UTC)
 _/ |\__'_|_|_|__'_|  |  mn/newrepl/fd19a97\* (fork: 10 commits, 1 day)
|__/                   |  x86_64-w64-mingw32

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating cache of Color...
INFO: Updating cache of Images...
INFO: Updating Readline...
INFO: Updating Terminals...
INFO: Updating REPLCompletions...
INFO: Computing changes...
INFO: Upgrading Color: v0.2.8 => v0.2.9
INFO: Upgrading DataArrays: v0.1.3 => v0.1.4
INFO: Upgrading Images: v0.2.32 => v0.2.34
INFO: Building Images

julia> exit()
blas_num_threads=4

C:\Julia\JuliaRepl\Julia 0.3.0-prerelease\bin>julia-basic c:/users/Jacques/.juli
a/v0.3/REPL/scripts/repl.jl
ERROR: spawn: no such file or directory (ENOENT)
 in _jl_spawn at process.jl:212
while loading c:\users\Jacques.julia\v0.3\REPL\scripts\repl.jl, in expression s
tarting on line 8

blas_num_threads=4

C:\Julia\JuliaRepl\Julia 0.3.0-prerelease\bin>

**Comment by nolta** [comment]
@jariou ihnorton's prebundled version already includes REPL.jl, so you don't need to run `scripts\repl.jl`.

**Comment by StefanKarpinski** [comment]
Yes, in this version, you just run `julia` normally you get the new REPL.

**Comment by jariou** [comment]
Ah ok.

I get it now. Sorry for the bother. It looks good. Anything I can do to help?

**Comment by nolta** [comment]
Just try it out, and let us know if you find any problems. Thanks!

**Comment by waldyrious** [comment]
For reference: This is now closed because JuliaLang/julia#6270 has been merged.
